# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    desc: Run api
    cmds:
      - go run cmd/api/main.go
  lint:
    desc: Lint project
    cmds:
      - golangci-lint run ./...
